### ISSUE TITLE
Feature request: Add Crowd support

### ISSUE THREAD

**Issue by webwesen** [echocat/adam#39]
reading and poking around brought me to a conclusion that Adam does not yet support Confluence instances hooked into [Crowd] (https://www.atlassian.com/software/crowd/overview) or with multiple directories (internal + Crowd).

please consider adding Crowd support

**Comment by blaubaer** [comment]
For now I have to mark it as wan't fix. Because I have right now no idea how to do this. If someone have an implementation idea please provide and reopen.
