### ISSUE TITLE
Disabled users

### ISSUE THREAD

**Issue by hroch** [echocat/adam#45]
It is possible to add disabled users to Reports? They are excluded from that by default. For example as an parameter of the Report?

Example
```xml
<report id="all" showActiveUsers="ture" showDisabledUsers="ture">
        <localization locale="en_US" title="All users" />
        <localization locale="de_DE" title="Alle Nutzer" />
        <access>
            <anonymous view="forbidden" />
            <default view="allowed" />
        </access>
 </report>
```
Then admin could define reports of Active, Disabled or both. Such overview might come handy when we want to someone re-hire or contact him from any other reason. Also brings some insight into fluctuation.

Then it would be great if such info could be present as an profile element. When someone is reviewing user profile it is not obvious if the user is active - another element could clarify it.

When i click user mentioned on Confluence page or shown as an author I can see this:
![1](https://cloud.githubusercontent.com/assets/7569389/4402148/b46288f6-4494-11e4-8428-abdf9dbf5988.JPG)
No idea if the user is active or not. Should I contact him?

**Comment by blaubaer** [comment]
This is not possible. This information is not provided at this position where the plugin are added to the system. :-(
