### ISSUE TITLE
Question: API call for user data from echocat ADAM

### ISSUE THREAD

**Issue by tlamiczka** [echocat/adam#59]
Hi,
is there any way how to get user data created by echocat ADAM via api call? (like phone number etc.) If I use REST API call in this format:

> `https://<CONFLUENCE URL>/rest/prototype/1/search/user.json?query=<USERNAME>
`

I get only standard fields, but not those made by ADAM. Is there any chance who to get full profile/all data?

thanks :-)

**Comment by blaubaer** [comment]
Hi @tlamiczka, currently this feature is not implemented but I expect this shouldn't be to hard to implement. If you want this feature please create a feature request with more details (examples of the respond json etc.) or with a pull request by your own. 😺
