### ISSUE TITLE
Not compatible with Confluence 7

### ISSUE THREAD

**Issue by jprusch** [echocat/adam#75]
The current version 0.1.14 in this repo is not compatible with Confluence 7 & will not allow anyone to login into Confluence after migration.
The version 0.1.15 of @alexat (https://github.com/alexat/adam/releases) fixes this issue, but the Persons page is still not working. An error 500 is thrown.
Error from application log:
`Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.echocat.adam.configuration.ConfigurationMarshaller
	at org.echocat.adam.configuration.ConfigurationRepository.getInternal(ConfigurationRepository.java:103)
	at org.echocat.adam.configuration.ConfigurationRepository.get(ConfigurationRepository.java:73)
	at org.echocat.adam.report.ReportProvider.getConfiguration(ReportProvider.java:564)
	at org.echocat.adam.report.ReportProvider.tryProvideViewable(ReportProvider.java:97)
	at org.echocat.adam.profile.ExtendedPeopleDirectoryAction.getEffectiveReport(ExtendedPeopleDirectoryAction.java:308)
	at org.echocat.adam.profile.ExtendedPeopleDirectoryAction.doBrowse(ExtendedPeopleDirectoryAction.java:97)
	... 393 more

2020-02-14 14:31:34,707 INFO [ajp-nio-xxx.xxx.xxx.xxx-8009-exec-12] [atlassian.confluence.status.SystemErrorInformationLogger] writeToLog 
Request Information
URL: https://SERVER/confluence/500page.jsp
Scheme: https
Server: SERVER
Port: 443
URI: /confluence/500page.jsp
Context Path: /confluence
Servlet Path: /500page.jsp
Path Info: null
Query String: null
Attributes
javax.servlet.forward.request_uri: /confluence/browsepeople.action
javax.servlet.forward.context_path: /confluence
javax.servlet.forward.servlet_path: /browsepeople.action
javax.servlet.forward.mapping: org.apache.catalina.core.ApplicationMapping$MappingImpl@6fe7c647
javamelody.injectorWrapped: true
javax.servlet.error.status_code: 500
com.atlassian.confluence.impl.profiling.DecoratorTimings: com.atlassian.confluence.impl.profiling.DecoratorTimings@24f67dc2
com.opensymphony.sitemesh.APPLIED_ONCE: true
__cleanup_recursion_counter: 0
com.atlassian.confluence.util.message.MessagesDecoratorFilter__already_filtered__: true
com.atlassian.confluence.web.filter.validateparam.RequestParamValidationFilter_already_filtered: true
atlassian.core.seraph.original.url: /500page.jsp
com.atlassian.labs.botkiller.BotKillerFilter: true
com.atlassian.gzipfilter.GzipFilter_already_filtered: true
Confluence-Request-Time: 1581687093586
javamelody.request: /browsepeople.action GET
com.atlassian.confluence.web.ConfluenceJohnsonFilter_already_filtered: true
com.atlassian.seraph.auth.LoginReason: OK
webwork.valueStack: com.opensymphony.xwork.util.OgnlValueStack@61002f9f
confluence.themecontext: com.atlassian.confluence.themes.ThemeContext@ecff5ee
javax.servlet.error.message: 
javax.servlet.error.servlet_name: action
com.opensymphony.sitemesh.USINGSTREAM: false
B3-TraceId: 8cc53030127109
loginfilter.already.filtered: true
javax.servlet.jsp.jspException: java.lang.reflect.InvocationTargetException
javax.servlet.error.request_uri: /confluence/browsepeople.action
com.atlassian.core.filters.HeaderSanitisingFilter_already_filtered: true
com.atlassian.prettyurls.filter.PrettyUrlsSiteMeshFixupFilter: true
javax.servlet.error.exception: java.lang.reflect.InvocationTargetException
os_securityfilter_already_filtered: true
com.atlassian.prettyurls.filter.PrettyUrlsSiteMeshFilter: true
Parameters
caused by: java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
caused by: java.lang.NoClassDefFoundError: Could not initialize class org.echocat.adam.configuration.ConfigurationMarshaller
at org.echocat.adam.configuration.ConfigurationRepository.getInternal(ConfigurationRepository.java:103)`
Any ideas?

**Comment by cwittenb** [comment]
I ran into the same issue these days.
Digging into it I found that the issue was caused by a NullPointer raised in org.eclipse.persistence, maybe related to Java11?
Anyway, I updated the pom to use the latest version 2.7.6 and rebuild the project.

So far everything working as expected again.
Hope this helps someone! See you again with the next confluence upgrade.

**Comment by jprusch** [comment]
Great, made my day. Would you send/mail me the jar?!?

**Comment by cwittenb** [comment]
Sure, give this one a try ...
[adam-0.1.15.jar.zip](https://github.com/echocat/adam/files/4450259/adam-0.1.15.jar.zip)

**Comment by jprusch** [comment]
THANK YOU! This solved my last blocker from moving to Confluence 7. Much appreciated!

**Comment by cwittenb** [comment]
:thumbsup: great!

**Comment by cwittenb** [comment]
You may have a look at the changes here:
https://github.com/cwittenb/adam/
Release is here:
https://github.com/cwittenb/adam/releases/tag/0.1.15

**Comment by jprusch** [comment]
Will check it out! Thanks
